---
- name: Disable auto-updates
  become: yes
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: 0644
    owner: root

- name: Update host
  become: yes
  apt:
    upgrade: dist
    force_apt_get: yes
    update_cache: yes
