---
- name: Disable swap in host
  become: yes
  command: swapoff -a

- name: Disable swap at fstab
  become: yes
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^/swapfile'

- name: Enable br_netfilter module load
  become: yes
  copy:
    dest: "/etc/modules-load.d/k8s.conf"
    content: |
      br_netfilter

- name: Load module br_netfilter
  become: yes
  modprobe:
    name: br_netfilter
    state: present


- name: Modify bridge-nf-call sysctl values
  become: yes
  copy:
    dest: "/etc/sysctl.d/k8s.conf"
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Enable sysctl IPv4 Forward
  become: yes
  copy:
    dest: "/etc/sysctl.d/ipv4_forward.conf"
    content: |
      net.ipv4.ip_forward=1

- name: Reload sysctl
  become: yes
  command: sysctl --system

- name: Install dependencies
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - containerd
      - ca-certificates
      - apt-transport-https
      - curl

- name: Add Google Cloud signing key
  become: yes
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Install K8s APT repo
  become: yes
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: k8s

- name: Install kubeadm and friends
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - kubelet=1.23.3-00
      - kubectl=1.23.3-00
      - kubeadm=1.23.3-00

- name: Hold kubeadm and friends
  become: yes
  dpkg_selections:
    selection: hold
    name: "{{ item }}"
  loop:
    - kubelet
    - kubectl
    - kubeadm
