---
- name: Disable swap in host
  become: yes
  command: swapoff -a

- name: Disable swap at fstab
  become: yes
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^/swapfile'

- name: Enable br_netfilter module load
  become: yes
  copy:
    dest: "/etc/modules-load.d/k8s.conf"
    content: |
      br_netfilter

- name: Load module br_netfilter
  become: yes
  modprobe:
    name: br_netfilter
    state: present

- name: Modify bridge-nf-call sysctl values and enable sysctl IPv4 Forward
  become: yes
  sysctl:
    sysctl_file: /etc/sysctl.d/k8s.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
  loop:
    - { name: net.ipv4.ip_forward, value: 1 }
    - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }
    - { name: net.bridge.bridge-nf-call-iptables, value: 1 }

- name: Install GnuPG
  become: yes
  apt:
    name: gpg

- name: Install CRI-O APT signing keys
  become: yes
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.26/xUbuntu_20.04/Release.key
    - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key

- name: Install CRI-O APT repos
  become: yes
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename }}"
  loop:
    - {
        repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /,
        filename: devel:kubic:libcontainers:stable,
      }
    - {
        repo: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/xUbuntu_20.04/ /,
        filename: devel:kubic:libcontainers:stable:cri-o:1.26,
      }

- name: Install dependencies
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - ca-certificates
      - curl
      - cri-o
      - cri-o-runc

- name: Enable crio service now
  become: yes
  systemd:
    name: crio
    enabled: yes
    state: started

- name: Add Google Cloud signing key
  become: yes
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Install K8s APT repo
  become: yes
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: k8s

- name: Install kubeadm and friends
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - kubelet=1.26.0-00
      - kubectl=1.26.0-00
      - kubeadm=1.26.0-00

- name: Hold kubeadm and friends
  become: yes
  dpkg_selections:
    selection: hold
    name: "{{ item }}"
  loop:
    - kubelet
    - kubectl
    - kubeadm

- name: Enable useful alias and autocompletion
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/etc/profile.d/{{ item }}"
  loop:
    - k8s.sh

- name: Prime docker image cache
  become: yes
  command: kubeadm config images pull --kubernetes-version 1.26.0
