---
- name: Disable swap in host
  become: yes
  command: swapoff -a

- name: Disable swap at fstab
  become: yes
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^/swapfile'

- name: Enable br_netfilter module load
  become: yes
  copy:
    dest: "/etc/modules-load.d/k8s.conf"
    content: |
      br_netfilter

- name: Load module br_netfilter
  become: yes
  modprobe:
    name: br_netfilter
    state: present

- name: Modify bridge-nf-call sysctl values and enable sysctl IPv4 Forward
  become: yes
  sysctl:
    sysctl_file: /etc/sysctl.d/k8s.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
  loop:
    - { name: net.ipv4.ip_forward, value: 1 }
    - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }
    - { name: net.bridge.bridge-nf-call-iptables, value: 1 }

- name: Install GnuPG
  become: yes
  apt:
    name: gpg

- name: Install dependencies
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - ca-certificates
      - curl
      - software-properties-common
      - jq
      - curl
      - wget
      - tmux

# https://wiki.debian.org/DebianRepository/UseThirdParty
- name: Create /etc/apt/keyrings
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add Google Cloud signing key
  become: yes
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc

- name: Install K8s APT repo
  become: yes
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present
    filename: k8s

- name: Add CRI-O signing key
  become: yes
  get_url:
    url: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.30/deb/Release.key
    dest: /etc/apt/keyrings/cri-o-apt-keyring.asc

- name: Install CRI-O APT repo
  become: yes
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.asc] https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.30/deb/ /"
    state: present
    filename: cri-o

- name: Install CRIU APT repo
  become: yes
  apt_repository:
    repo: 'ppa:criu/ppa'
    state: present
    filename: criu

- name: Install runtime dependencies
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - crun
      - runc
      - criu
      - conmon
      - containerd

- name: Install kubeadm and friends
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      # - cri-o=1.30.0-1.1
      - kubelet=1.30.0-1.1
      - kubectl=1.30.0-1.1
      - kubeadm=1.30.0-1.1

# - name: Enable crio service now
#   become: yes
#   systemd:
#     name: crio
#     enabled: yes
#     state: started

- name: Hold kubeadm and friends
  become: yes
  dpkg_selections:
    selection: hold
    name: "{{ item }}"
  loop:
    - kubelet
    - kubectl
    - kubeadm

- name: Enable useful alias and autocompletion
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/etc/profile.d/{{ item }}"
  loop:
    - k8s.sh

- name: Prime docker image cache
  become: yes
  command: kubeadm config images pull --kubernetes-version 1.30.0
